config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :stocks, only: %i[index show new create]
  resources :accounts, only: %i[index show] do
    post :import_activity
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  belongs_to :owner
  has_many :trades
  has_many :drips, -> { where type: "Drip" }, class_name: "Trade"
  has_many :buys, -> { where type: %w[Buy Drip] }, class_name: "Trade"
  has_many :sells, -> { where type: "Sell" }, class_name: "Trade"
  has_many :transactions
  has_many :deposits, -> { where type: "Deposit" }, class_name: "Transaction"
  has_many :withdrawals, -> { where type: "Withdrawal" }, class_name: "Transaction"
  has_many :dividends
  has_many :stocks, through: :trades
  has_many :conversions

  def bought_positions(date: Date.today)
    buys.where(datetime: ..date).group_by(&:stock).transform_values do |value|
      bought_shares = value.sum(&:shares)
      average_price = value.sum do |trade|
        trade.shares * trade.price
      end / bought_shares
      {
        shares: bought_shares,
        price: average_price
      }
    end
  end

  def sold_positions(date: Date.today)
    @sold_positions ||= sells.where(datetime: ..date).group_by(&:stock).transform_values do |value|
      sold_shares = value.sum(&:shares)
      average_price = value.sum do |trade|
        trade.shares * trade.price
      end / sold_shares
      {
        shares: sold_shares,
        price: average_price
      }
    end
  end

  def all_positions(date: Date.today)
    bought_positions(date:).map do |stock, value|
      sold_position = sold_positions(date:)[stock]
      sold_shares = sold_position.nil? ? 0 : sold_position[:shares]
      net_shares = value[:shares] - sold_shares
      price = value[:price]
      sold_price = (sold_position.nil? ? "-" : sold_position[:price])
      total_dividends = stock.dividends.where(datetime: date).total_value_by_account(self)
      live_price = stock.live_price
      current_value = live_price ? net_shares * live_price : 0
      book_value = net_shares * value[:price]
      {
        stock:,
        ticker: stock.ticker,
        shares: net_shares,
        price: price.to_f / 100,
        current_price: live_price ? live_price.to_f / 100 : "-",
        book_value: book_value.to_f / 100,
        current_value: live_price ? (net_shares * live_price).to_f / 100 : "-",
        sold_shares:,
        sold_price: sold_price.to_f / 100,
        total_dividends: total_dividends.to_f / 100,
        closed_position_p_n_l: net_shares.zero? ? ((sold_price - price) * sold_shares + total_dividends).to_f / 100 : "-",
        live_p_n_l: (current_value - book_value + total_dividends).to_f / 100
      }
    end
  end

  def sorted_all_postions(direction:, column:)
    sorted = all_positions.sort_by { |p| p[column] }
    return sorted if direction == :asc

    sorted.reverse
  end

  def money_formatter(value)
    return value unless value.is_a? Integer

    "$#{value.to_f / 100}"
  end

  def total_dividends
    @total_dividends ||= dividends.sum(:amount)
  end

  def total_dividends_dollars
    total_dividends.to_f / 100
  end

  def sum_deposits
    @sum_deposits ||= deposits.sum(:amount)
  end

  def sum_deposits_dollars
    sum_deposits.to_f / 100
  end

  def sum_withdrawals
    @sum_withdrawals ||= withdrawals.sum(:amount)
  end

  def sum_withdrawals_dollars
    sum_withdrawals.to_f / 100
  end

  def net_deposits
    @net_deposits ||= sum_deposits - sum_withdrawals
  end

  def net_deposits_dollars
    net_deposits.to_f / 100
  end

  def snowball_percentage
    @snowball_percentage ||= ((total_dividends / net_deposits.to_f) * 100).round(4)
  end

  def first_deposit_date
    @first_deposit_date ||= deposits.order(:datetime).first.datetime.to_date
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buy.rb
# frozen_string_literal: true

class Buy < Trade
end

app/models/conversion.rb
# frozen_string_literal: true

class Conversion < ApplicationRecord
  belongs_to :account
end

app/models/deposit.rb
# frozen_string_literal: true

class Deposit < Transaction
end

app/models/dividend.rb
# frozen_string_literal: true

class Dividend < ApplicationRecord
  belongs_to :account
  belongs_to :stock

  scope :for_stock_in_account, ->(stock, account) { where(stock:, account:) }
  scope :total_value_by_account, ->(account) { where(account:).sum(:amount) }
end

app/models/drip.rb
# frozen_string_literal: true

class Drip < Trade
end

app/models/interest.rb
# frozen_string_literal: true

class Interest < Transaction
end

app/models/owner.rb
# frozen_string_literal: true

class Owner < ApplicationRecord
  has_many :accounts

  def name
    "#{firstname} #{lastname}"
  end
end

app/models/sell.rb
# frozen_string_literal: true

class Sell < Trade
end

app/models/stock.rb
# frozen_string_literal: true

class Stock < ApplicationRecord
  has_many :trades
  has_many :dividends

  def self.fresh_market_data
    all.each do |stock|
      YahooPriceScraper.new(stock:).update_market_data
    end
  end
end

app/models/trade.rb
# frozen_string_literal: true

class Trade < ApplicationRecord
  belongs_to :stock
  belongs_to :account
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  belongs_to :account
end

app/models/withdrawal.rb
# frozen_string_literal: true

class Withdrawal < Transaction
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account
               .includes(:deposits, :withdrawals, dividends: :stock, trades: :stock)
               .find(params[:id])

    @positions = positions
    @current_positions = positions.select { |p| p[:shares].positive? }
    @closed_positions = positions.reject { |p| p[:shares].positive? }
    @current_value = @current_positions.map { |p| p[:current_value] }.reject { |v| v == "-" }.sum
    @last_dividends = @account.dividends.order(datetime: :desc).first(50)
    @trades = @account.trades.order(datetime: :desc)
    @first_deposit_date = @account.deposits.order(:datetime).first
  end

  def positions
    direction = params.dig(:sort, :direction)&.to_sym || :asc
    column = params.dig(:sort, :column)&.to_sym || :ticker
    @account.sorted_all_postions(direction:, column:)
  end

  def import_activity
    return redirect_to request.referer, notice: "No file added" if params[:file].nil?
    return redirect_to request.referer, notice: "Only CSV files allowed" unless params[:file].content_type == "text/csv"

    CsvImportActivityService.new.call(params[:file], import_account)

    redirect_to request.referer, notice: "Import started..."
  end

  private

  def import_account
    Account.find(params[:account_id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/stocks_controller.rb
# frozen_string_literal: true

class StocksController < ApplicationController
  def index
    @stocks = Stock.all.order(:ticker)
  end

  def show
    @stock = Stock.find(params[:id])
  end

  def new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_params)
    return unless @stock.save

    redirect_to stocks_path
  end

  private

  def stock_params
    params.require(:stock).permit(:ticker, :currency)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/accounts/_import_activity.html.erb
<%= form_tag account_import_activity_path(@account), method: :post, multipart: true do %>
  <%= file_field_tag :file, accept: ".csv" %>
  <%= submit_tag 'Import' %>
<% end %>

app/views/accounts/index.html.erb
<h1>Accounts#index</h1>
<p>Find me in app/views/accounts/index.html.erb</p>
<table>
  <thead>
    <tr>
      <th>Account Name</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
<% @accounts.each do |account| %>
    <tr>
    <td><%= account.name %></td>
    <td><%= account.owner.name %></td>
    <td><%= link_to "Go", { action: :show, id: account.id}, method: :get %></td>
    </tr>
<% end %>
</tbody>
</table>

app/views/accounts/show.html.erb
<h1><a href='/accounts/'> Accounts: </a><%= @account.name %></h1>
<table>
  <thead>
    <tr>
      <th>Net Deposits</th>
      <th>Current Value</th>
      <th>Gain %</th>
      <th>First Deposit Date</th>
      <th>Total Dividends</th>
      <th>Snowball Percentage</th>
    </tr>
  </thead>
<tbody>
    <tr>
    <td>$<%= number_with_delimiter(@account.net_deposits_dollars, delimiter: ",", precision: 2) %></td>
    <td>$<%= number_with_delimiter(@current_value, delimiter: ",", precision: 2) %></td>
    <td><%= ((@current_value / @account.net_deposits_dollars - 1) * 100).round(4) %>%</td>
    <td><%= @account.first_deposit_date %></td>
    <td>$<%= number_with_delimiter(@account.total_dividends_dollars, delimiter: ",", precision: 2) %></td>
    <td><%= @account.snowball_percentage %>%</td>
    </tr>
</tbody>
</table>

<%= render "import_activity" %>

<h3>Active Positions</h3>
<table>
  <thead>
        <tr>
            <th>Ticker</th>
            <th>Shares</th>
            <th>Book Price</th>
            <th>Current Price</th>
            <th>
              <a href="<%= '/accounts/' + @account.id.to_s + '/?sort[column]=book_value&sort[direction]=asc' %>">	&uArr; </a>
                Book Value
              <a href="<%= '/accounts/' + @account.id.to_s + '/?sort[column]=book_value&sort[direction]=desc' %>"> &dArr; </a>
            </th>
            <th>
              <a href="<%= '/accounts/' + @account.id.to_s + '/?sort[column]=current_value&sort[direction]=asc' %>">	&uArr; </a>
                Current Value
              <a href="<%= '/accounts/' + @account.id.to_s + '/?sort[column]=current_value&sort[direction]=desc' %>"> &dArr; </a>
            </th>
            <th>Sold Shares</th>
            <th>Sold Price</th>
            <th>
              <a href="<%= '/accounts/' + @account.id.to_s + '/?sort[column]=total_dividends&sort[direction]=asc' %>">	&uArr; </a>
                Total Dividends
              <a href="<%= '/accounts/' + @account.id.to_s + '/?sort[column]=total_dividends&sort[direction]=desc' %>"> &dArr; </a>
            </th>
            <th>
              <a href="<%= '/accounts/' + @account.id.to_s + '/?sort[column]=live_p_n_l&sort[direction]=asc' %>">	&uArr; </a>
                Current PnL
              <a href="<%= '/accounts/' + @account.id.to_s + '/?sort[column]=live_p_n_l&sort[direction]=desc' %>"> &dArr; </a>
            </th>
        </tr>
  </thead>
<tbody>
<% @current_positions.each do |data| %>
    <tr>
    <td><%= data[:ticker] %></td>
    <td><%= data[:shares] %></td>
    <td>$<%= number_with_delimiter(data[:price], delimiter: ",", precision: 2) %></td>
    <td>$<%= number_with_delimiter(data[:current_price], delimiter: ",", precision: 2) %></td>
    <td>$<%= number_with_delimiter(data[:book_value], delimiter: ",", precision: 2) %></td>
    <td>$<%= number_with_delimiter(data[:current_value], delimiter: ",", precision: 2) %></td>
    <td><%= data[:sold_shares] %></td>
    <td>$<%= number_with_delimiter(data[:sold_price], delimiter: ",", precision: 2) %></td>
    <td>$<%= number_with_delimiter(data[:total_dividends], delimiter: ",", precision: 2) %></td>
    <td>$<%= number_with_delimiter(data[:live_p_n_l], delimiter: ",", precision: 2) %></td>
    </tr>
<% end %>
</tbody>
</table>

<h3>Buys and Sells</h3>
<table>
  <thead>
        <tr>
            <th>Type</th>
            <th>Ticker</th>
            <th>Shares</th>
            <th>Price</th>
            <th>Date</th>
        </tr>
  </thead>
  <tbody>
  <% @trades.each do |data| %>
  <tr>
    <td><%= data.type %></td>
    <td><%= data.stock.ticker %></td>
    <td><%= data.shares %></td>
    <td><%= number_with_delimiter(data.price, delimiter: ",", precision: 2) %></td>
    <td><%= data.datetime.to_date %></td>
  </tr>
  <% end %>
  </tbody>
<table>

<h3>Closed Positions</h3>
<table>
  <thead>
        <tr>
            <th>Ticker</th>
            <th>Shares</th>
            <th>Price</th>
            <th>Book Value</th>
            <th>Sold Shares</th>
            <th>Sold Price</th>
            <th>Total Dividends</th>
            <th>Closed Position PnL</th>
        </tr>
  </thead>
<tbody>
<% @closed_positions.each do |data| %>
    <tr>
    <td><%= data[:ticker] %></td>
    <td><%= data[:shares] %></td>
    <td><%= data[:price] %></td>
    <td><%= data[:book_value] %></td>
    <td><%= data[:sold_shares] %></td>
    <td><%= data[:sold_price] %></td>
    <td><%= data[:total_dividends] %></td>
    <td><%= data[:closed_position_p_n_l] %></td>
    </tr>
<% end %>
</tbody>
</table>

<h3>Dividend History</h3>
<table>
  <thead>
        <tr>
            <th>Ticker</th>
            <th>Amount</th>
            <th>Date</th>
        </tr>
  </thead>
<tbody>
<% @last_dividends.each do |data| %>
    <tr>
    <td><%= data.stock[:ticker] %></td>
    <td><%= data[:amount] %></td>
    <td><%= data[:datetime] %></td>
    </tr>
<% end %>
</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalTrading</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stocks/index.html.erb
<h1>Stocks#index</h1>
<button><%= link_to "Add Stock", new_stock_path, method: :get %> </button>
<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Currency</th>
      <th>Price</th>
      <th>Last Updated</th>
    </tr>
  </thead>
<tbody>
<% @stocks.each do |stock| %>
    <tr>
    <td><%= link_to stock.ticker, { action: :show, id: stock.id}, method: :get %></td>
    <td><%= stock.currency %></td>
    <td><%= stock.live_price %></td>
    <td><%= stock.live_price_as_of %></td>
    </tr>
<% end %>
</tbody>
</table>

app/views/stocks/new.html.erb
<h1>Stocks#new</h1>
<p>Find me in app/views/stocks/new.html.erb</p>
<%= form_with model: @stock do |form| %>
  <%= form.text_field :ticker %>
  <%= form.select :currency, { "CAD" => "CAD", "USD" => "USD"}, selected: "CAD" %>
  <%= form.submit %>
<% end %>

app/views/stocks/show.html.erb
<h1>Stocks#show</h1>

<h2><%= @stock.ticker %></h2>